version: '3'
services:
  front:
    image: ci-tool-stack/nginx:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.${VERSION:-latest}
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
    ports:
      - "80"
    environment:
      - http_proxy=$http_proxy
      - https_proxy=$https_proxy
      - no_proxy=$no_proxy,nexus
#    volumes:
#       - $NGINX_CONFIG:/etc/nginx/conf.d/default.conf:ro
